### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ryannix123** [Microsoft/openshift-origin#10]
Hi All,

Any chance you could add the metrics to the OpenShift deploy parameters so it's automatically installed by default? https://docs.openshift.com/container-platform/3.4/install_config/cluster_metrics.html

Thanks!

Ryan

**Comment by haroldwongms** [comment]
We are trying to keep the OpenShift Origin template as simple as possible.  As it is, I'm considering making the Azure integration an optional component as that is causing challenges for those who don't want that auto-configured.

I will let Boris weigh in on this as well.

**Comment by ryannix123** [comment]
Which Azure integrations would be optional? AzureAD and Blob storage? Optional is fine, but I hope those features aren't removed because deployment is so much easier with them in there! Certainly identity management is important. Additionally, Origin can't do as much if it doesn't have persist volumes, so I feel like Blob storage is a must too.

**Comment by ryannix123** [comment]
Going back to the metrics request, it would be great to have them in the deployment scripts as it's a terrific feature to have in OpenShift. I'm kind of surprised that Redhat doesn't have that enabled in the install.

**Comment by lestaat** [comment]
Found many issues in try to build up the OpenShift Origin shipped into Azure

DeployOpenshift.sh fails on many points, let me enumerate some:

1- Openshift versions is old, it fails cause it require 1.5.1
2- VMs size is wrong it ask for bigger resources in some filesystems and memory

**Comment by ryannix123** [comment]
@haroldwongms @BorisB2015 I think there is a pull request to update the version of OpenShift.

**Comment by lestaat** [comment]
Gotcha,

Some more details in failures I got, I've chosen a different VM size but problems still remains, ansible playbooks for config are not supporting the base filesystem layout alongside reporting missing ca cert

ailure summary:

  1. Host:     myocluster-master-0
     Play:     Verify Requirements
     Task:     openshift_health_check
     Message:  One or more checks failed
     Details:  check "disk_availability":
               Available disk space (29.6 GB) for the volume containing "/var" is below minimum recommended space (40.0 GB)

  2. Host:     myocluster-infra-0
     Play:     Configure nodes
     Task:     openshift_node_certificates : fail
     Message:  CA certificate /etc/origin/master/ca.crt doesn't exist on CA host myocluster-master-0. Apply 'openshift_ca' role to myocluster-master-0.

**Comment by eekwong** [comment]
> I think there is a pull request to update the version of OpenShift.
It seems there's only one location that's changed to v1.5.1, which is the single master configuration. There's another location with "v1.5".

**Comment by haroldwongms** [comment]
master branch for Origin 3.7 now supports option to deploy metrics and logging.  The OS disk size is now increased to 64 GB so pre-requisite checks will no longer fail.

I will look into updating release-3.6 branch to include some of these changes as well.
