### ISSUE TITLE
OKD failed on azure with 1-master,1-infra and 2 worker nodes

### ISSUE THREAD

**Issue by sureshadapa** [Microsoft/openshift-origin#107]

**Comment by sureshadapa** [comment]
1.
Also unable to login to master node using 
ssh -p 2200 clusteradmin@<masterdns.*****.eastus.cloudapp.azure.com>


2.

Deployment failed. Correlation ID: 702a69df-5896-42fa-983d-da58f9dad010. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "Conflict",
            "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'deployOpenShift'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=4\\n[stdout]\\n*****\\n\\nTASK [Evaluate groups - g_node_hosts or g_new_node_hosts required] *************\\n\\nTASK [Evaluate groups - g_lb_hosts required] ***********************************\\n\\nTASK [Evaluate groups - g_nfs_hosts required] **********************************\\n\\nTASK [Evaluate groups - g_nfs_hosts is single host]****************************\\n\\nTASK [Evaluate groups - g_glusterfs_hosts required] ****************************\\n\\nTASK [Evaluate groups - Fail if no etcd hosts group is defined] ****************\\n\\nTASK [Evaluate oo_all_hosts] ***************************************************\\nok: [localhost] => (item=suresh-master-0)\\nok: [localhost] => (item=suresh-infra-0)\\nok: [localhost] => (item=suresh-node-0)\\nok: [localhost] => (item=suresh-node-1)\\n\\nTASK [Evaluate oo_masters] *****************************************************\\nok: [localhost] => (item=suresh-master-0)\\n\\nTASK [Evaluate oo_first_master] ************************************************\\nok: [localhost]\\n\\nTASK [Evaluate oo_new_etcd_to_config] ******************************************\\n\\nTASK [Evaluate oo_masters_to_config] *******************************************\\nok: [localhost] => (item=suresh-master-0)\\n\\nTASK [Evaluate oo_etcd_to_config] **********************************************\\nok: [localhost] => (item=suresh-master-0)\\n\\nTASK [Evaluate oo_first_etcd] **************************************************\\nok: [localhost]\\n\\nTASK [Evaluate oo_etcd_hosts_to_upgrade] ***************************************\\nok: [localhost] => (item=suresh-master-0)\\n\\nTASK [Evaluate oo_etcd_hosts_to_backup] ****************************************\\nok: [localhost] => (item=suresh-master-0)\\n\\nTASK [Evaluate oo_nodes_to_config] *********************************************\\nok: [localhost] => (item=suresh-master-0)\\nok: [localhost] => (item=suresh-infra-0)\\nok: [localhost] => (item=suresh-node-0)\\nok: [localhost] => (item=suresh-node-1)\\n\\nTASK [Add master to oo_nodes_to_config] ****************************************\\n\\nTASK [Evaluate oo_lb_to_config] ************************************************\\n\\nTASK [Evaluate oo_nfs_to_config] ***********************************************\\n\\nTASK [Evaluate oo_glusterfs_to_config] *****************************************\\n\\nTASK [Evaluate oo_etcd_to_migrate] *********************************************\\nok: [localhost] => (item=suresh-master-0)\\n\\nPLAY [Install and configure NetworkManager] ************************************\\n\\nTASK [Gathering Facts] *********************************************************\\nfatal: [suresh-master-0]: UNREACHABLE! => {\\\"changed\\\": false, \\\"msg\\\": \\\"Failed to connect to the host via ssh: Warning: Permanently added 'suresh-master-0,10.1.0.5' (ECDSA) to the list of known hosts.\\\\r\\\\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic).\\\\r\\\\n\\\", \\\"unreachable\\\": true}\\nok: [suresh-node-0]\\nok: [suresh-node-1]\\nok: [suresh-infra-0]\\n\\nTASK [install NetworkManager] **************************************************\\nok: [suresh-node-0]\\nok: [suresh-node-1]\\nok: [suresh-infra-0]\\n\\nTASK [configure NetworkManager] ************************************************\\nchanged: [suresh-node-0] => (item=USE_PEERDNS)\\nchanged: [suresh-node-1] => (item=USE_PEERDNS)\\nchanged: [suresh-infra-0] => (item=USE_PEERDNS)\\nchanged: [suresh-node-0] => (item=NM_CONTROLLED)\\nchanged: [suresh-node-1] => (item=NM_CONTROLLED)\\nchanged: [suresh-infra-0] => (item=NM_CONTROLLED)\\n\\nTASK [enable and start NetworkManager] *****************************************\\nok: [suresh-node-0]\\nok: [suresh-node-1]\\nok: [suresh-infra-0]\\n\\tto retry, use: --limit @/home/clusteradmin/openshift-ansible/playbooks/openshift-node/network_manager.retry\\n\\nPLAY RECAP *********************************************************************\\nlocalhost                  : ok=11   changed=0    unreachable=0    failed=0   \\nsuresh-infra-0     : ok=4    changed=1    unreachable=0    failed=0   \\nsuresh-master-0            : ok=0    changed=0    unreachable=1    failed=0   \\nsuresh-node-0              : ok=4    changed=1    unreachable=0    failed=0   \\nsuresh-node-1              : ok=4    changed=1    unreachable=0    failed=0   \\n\\n\\n[stderr]\\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\\n                                 Dload  Upload   Total   Spent    Left  Speed\\n\\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\\r100     6  100     6    0     0    804      0 --:--:-- --:--:-- --:--:--   750\\r100     6  100     6    0    0    782      0 --:--:-- --:--:-- --:--:--   750\\n [WARNING]: provided hosts list is empty, only localhost is available. Note\\nthat the implicit localhost does not match 'all'\\n\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}

**Comment by sureshadapa** [comment]
{ "id": "/subscriptions/74015232-9b0e-4123-8d83-0150b72b20da/resourceGroups/ResourceGroup2/providers/Microsoft.Resources/deployments/OpenShiftDeployment/operations/CF4B6AFA95BBE1A9", "operationId": "CF4B6AFA95BBE1A9", "properties": { "provisioningOperation": "Create", "provisioningState": "Failed", "timestamp": "2019-02-09T11:41:37.7639451Z", "duration": "PT1M31.0508675S", "trackingId": "6b99d547-ccab-42d9-80a2-1005fc0ea5d7", "statusCode": "Conflict", "statusMessage": { "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'.", "details": [ { "code": "VMExtensionProvisioningError", "message": "VM has reported a failure when processing extension 'deployOpenShift'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=2\n[stdout]\nalhost] => (item=suresh-master-0)\nok: [localhost] => (item=suresh-master-1)\nok: [localhost] => (item=suresh-master-2)\n\nTASK [Evaluate oo_etcd_hosts_to_backup] ****************************************\nok: [localhost] => (item=suresh-master-0)\nok: [localhost] => (item=suresh-master-1)\nok: [localhost] => (item=suresh-master-2)\n\nTASK [Evaluate oo_nodes_to_config] *********************************************\nok: [localhost] => (item=suresh-master-0)\nok: [localhost] => (item=suresh-master-1)\nok: [localhost] => (item=suresh-master-2)\nok: [localhost] => (item=suresh-infra-0)\nok: [localhost] => (item=suresh-infra-1)\nok: [localhost] => (item=suresh-infra-2)\nok: [localhost] => (item=suresh-node-0)\nok: [localhost] => (item=suresh-node-1)\nok: [localhost] => (item=suresh-node-2)\n\nTASK [Add master to oo_nodes_to_config] ****************************************\n\nTASK [Evaluate oo_lb_to_config] ************************************************\n\nTASK [Evaluate oo_nfs_to_config] ***********************************************\n\nTASK [Evaluate oo_glusterfs_to_config] *****************************************\n\nTASK [Evaluate oo_etcd_to_migrate] *********************************************\nok: [localhost] => (item=suresh-master-0)\nok: [localhost] => (item=suresh-master-1)\nok: [localhost] => (item=suresh-master-2)\n\nPLAY [Install and configure NetworkManager] ************************************\n\nTASK [Gathering Facts] *********************************************************\nok: [suresh-master-2]\nok: [suresh-master-1]\nok: [suresh-master-0]\nok: [suresh-infra-1]\nok: [suresh-infra-0]\nok: [suresh-node-0]\nok: [suresh-node-2]\nok: [suresh-node-1]\nfatal: [suresh-infra-2]: FAILED! => {\"msg\": \"Timeout (12s) waiting for privilege escalation prompt: \"}\n\nTASK [install NetworkManager] **************************************************\nok: [suresh-master-1]\nok: [suresh-master-2]\nok: [suresh-master-0]\nok: [suresh-infra-1]\nok: [suresh-infra-0]\nok: [suresh-node-0]\nok: [suresh-node-1]\nok: [suresh-node-2]\n\nTASK [configure NetworkManager] ************************************************\nchanged: [suresh-master-1] => (item=USE_PEERDNS)\nchanged: [suresh-master-2] => (item=USE_PEERDNS)\nchanged: [suresh-master-0] => (item=USE_PEERDNS)\nchanged: [suresh-infra-0] => (item=USE_PEERDNS)\nchanged: [suresh-infra-1] => (item=USE_PEERDNS)\nchanged: [suresh-master-1] => (item=NM_CONTROLLED)\nchanged: [suresh-master-2] => (item=NM_CONTROLLED)\nchanged: [suresh-master-0] => (item=NM_CONTROLLED)\nchanged: [suresh-infra-0] => (item=NM_CONTROLLED)\nchanged: [suresh-infra-1] => (item=NM_CONTROLLED)\nchanged: [suresh-node-0] => (item=USE_PEERDNS)\nchanged: [suresh-node-1] => (item=USE_PEERDNS)\nchanged: [suresh-node-2] => (item=USE_PEERDNS)\nchanged: [suresh-node-0] => (item=NM_CONTROLLED)\nchanged: [suresh-node-2] => (item=NM_CONTROLLED)\nchanged: [suresh-node-1] => (item=NM_CONTROLLED)\n\nTASK [enable and start NetworkManager] *****************************************\nok: [suresh-master-1]\nok: [suresh-master-0]\nok: [suresh-master-2]\nok: [suresh-infra-0]\nok: [suresh-infra-1]\nok: [suresh-node-0]\nok: [suresh-node-1]\nok: [suresh-node-2]\n\tto retry, use: --limit @/home/clusteradmin/openshift-ansible/playbooks/openshift-node/network_manager.retry\n\nPLAY RECAP *********************************************************************\nlocalhost : ok=11 changed=0 unreachable=0 failed=0 \nsuresh-infra-0 : ok=4 changed=1 unreachable=0 failed=0 \nsuresh-infra-1 : ok=4 changed=1 unreachable=0 failed=0 \nsuresh-infra-2 : ok=0 changed=0 unreachable=0 failed=1 \nsuresh-master-0 : ok=4 changed=1 unreachable=0 failed=0 \nsuresh-master-1 : ok=4 changed=1 unreachable=0 failed=0 \nsuresh-master-2 : ok=4 changed=1 unreachable=0 failed=0 \nsuresh-node-0 : ok=4 changed=1 unreachable=0 failed=0 \nsuresh-node-1 : ok=4 changed=1 unreachable=0 failed=0 \nsuresh-node-2 : ok=4 changed=1 unreachable=0 failed=0 \n\n\n[stderr]\n % Total % Received % Xferd Average Speed Time Time Time Current\n Dload Upload Total Spent Left Speed\n\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\r100 6 100 6 0 0 853 0 --:--:-- --:--:-- --:--:-- 1000\n [WARNING]: provided hosts list is empty, only localhost is available. Note\nthat the implicit localhost does not match 'all'\n\"." } ] } }, "targetResource": { "id": "/subscriptions/74015232-9b0e-4123-8d83-0150b72b20da/resourceGroups/ResourceGroup2/providers/Microsoft.Compute/virtualMachines/suresh-master-0/extensions/deployOpenShift", "resourceType": "Microsoft.Compute/virtualMachines/extensions", "resourceName": "suresh-master-0/deployOpenShift" } }}

**Comment by zipper97412** [comment]
Hi, I have the same problem, let me know if you find something!

**Comment by sureshadapa** [comment]
ok, I got it working. 

I was using the "azuredeploy.parameters.json" as input parameters file, In which i had storageKind="managed", which was unable to create the storage fs, which i guess is "gluster FS" by default.So, I had changed it to unmanaged and it worked and was able to login to the OpenShiftOrigin (OKD-3.9) in Azure.

"storageKind": {
			"value": "unmanaged"
		},
