### ISSUE TITLE
Unable to deploy origin version 3.9 

### ISSUE THREAD

**Issue by satya2048** [microsoft/openshift-origin#114]
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'deployOpenShift'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=1\\n[stdout]\\n\\\", \\\"NoNewPrivileges\\\": \\\"no\\\", \\\"NonBlocking\\\": \\\"no\\\", \\\"NotifyAccess\\\": \\\"none\\\", \\\"OOMScoreAdjust\\\": \\\"0\\\", \\\"OnFailureJobMode\\\": \\\"replace\\\", \\\"PermissionsStartOnly\\\": \\\"no\\\", \\\"PrivateDevices\\\": \\\"no\\\", \\\"PrivateNetwork\\\": \\\"no\\\", \\\"PrivateTmp\\\": \\\"no\\\", \\\"ProtectHome\\\": \\\"no\\\", \\\"ProtectSystem\\\": \\\"no\\\", \\\"RefuseManualStart\\\": \\\"no\\\", \\\"RefuseManualStop\\\": \\\"no\\\", \\\"RemainAfterExit\\\": \\\"yes\\\", \\\"Requires\\\": \\\"basic.target\\\", \\\"Restart\\\": \\\"no\\\", \\\"RestartUSec\\\": \\\"100ms\\\", \\\"Result\\\": \\\"success\\\", \\\"RootDirectoryStartOnly\\\": \\\"no\\\", \\\"RuntimeDirectoryMode\\\": \\\"0755\\\", \\\"SameProcessGroup\\\": \\\"no\\\", \\\"SecureBits\\\": \\\"0\\\", \\\"SendSIGHUP\\\": \\\"no\\\", \\\"SendSIGKILL\\\": \\\"yes\\\", \\\"Slice\\\": \\\"system.slice\\\", \\\"SourcePath\\\": \\\"/etc/rc.d/init.d/network\\\", \\\"StandardError\\\": \\\"inherit\\\", \\\"StandardInput\\\": \\\"null\\\", \\\"StandardOutput\\\": \\\"journal\\\", \\\"StartLimitAction\\\": \\\"none\\\", \\\"StartLimitBurst\\\": \\\"5\\\", \\\"StartLimitInterval\\\": \\\"10000000\\\", \\\"StartupBlockIOWeight\\\": \\\"18446744073709551615\\\", \\\"StartupCPUShares\\\": \\\"18446744073709551615\\\", \\\"StatusErrno\\\": \\\"0\\\", \\\"StopWhenUnneeded\\\": \\\"no\\\", \\\"SubState\\\": \\\"exited\\\", \\\"SyslogLevelPrefix\\\": \\\"yes\\\", \\\"SyslogPriority\\\": \\\"30\\\", \\\"SystemCallErrorNumber\\\": \\\"0\\\", \\\"TTYReset\\\": \\\"no\\\", \\\"TTYVHangup\\\": \\\"no\\\", \\\"TTYVTDisallocate\\\": \\\"no\\\", \\\"TasksAccounting\\\": \\\"no\\\", \\\"TasksCurrent\\\": \\\"18446744073709551615\\\", \\\"TasksMax\\\": \\\"18446744073709551615\\\", \\\"TimeoutStartUSec\\\": \\\"5min\\\", \\\"TimeoutStopUSec\\\": \\\"5min\\\", \\\"TimerSlackNSec\\\": \\\"50000\\\", \\\"Transient\\\": \\\"no\\\", \\\"Type\\\": \\\"forking\\\", \\\"UMask\\\": \\\"0022\\\", \\\"UnitFilePreset\\\": \\\"disabled\\\", \\\"UnitFileState\\\": \\\"bad\\\", \\\"WantedBy\\\": \\\"graphical.target multi-user.target\\\", \\\"Wants\\\": \\\"network-online.target network.target system.slice\\\", \\\"WatchdogTimestampMonotonic\\\": \\\"0\\\", \\\"WatchdogUSec\\\": \\\"0\\\"}}\\nSat Aug 24 19:33:47 UTC 2019 - NetworkManager configuration complete\\n\\nPLAY [all] *********************************************************************\\n\\nTASK [make sure /etc/origin/cloudprovider exists] ******************************\\nchanged: [okd-master-0]\\n\\nTASK [populate /etc/origin/cloudprovider/azure.conf] ***************************\\nchanged: [okd-master-0]\\n\\nPLAY [all] *********************************************************************\\n\\nTASK [make sure /etc/origin/cloudprovider exists] ******************************\\nchanged: [okd-infra-0]\\n\\nTASK [populate /etc/origin/cloudprovider/azure.conf] ***************************\\nchanged: [okd-infra-0]\\n\\nPLAY [all] *********************************************************************\\n\\nTASK [make sure /etc/origin/cloudprovider exists] ******************************\\nchanged: [okd-infra-1]\\n\\nTASK [populate /etc/origin/cloudprovider/azure.conf] ***************************\\nchanged: [okd-infra-1]\\n\\nPLAY [all] *********************************************************************\\n\\nTASK [make sure /etc/origin/cloudprovider exists] ******************************\\nchanged: [okd-node-0]\\n\\nTASK [populate /etc/origin/cloudprovider/azure.conf] ***************************\\nchanged: [okd-node-0]\\n\\nPLAY [all] *********************************************************************\\n\\nTASK [make sure /etc/origin/cloudprovider exists] ******************************\\nchanged: [okd-node-1]\\n\\nTASK [populate /etc/origin/cloudprovider/azure.conf] ***************************\\nchanged: [okd-node-1]\\n\\nPLAY RECAP *********************************************************************\\nokd-infra-0 : ok=2 changed=2 unreachable=0 failed=0 skipped=0 rescued=0 ignored=0 \\nokd-infra-1 : ok=2 changed=2 unreachable=0 failed=0 skipped=0 rescued=0 ignored=0 \\nokd-master-0 : ok=2 changed=2 unreachable=0 failed=0 skipped=0 rescued=0 ignored=0 \\nokd-node-0 : ok=2 changed=2 unreachable=0 failed=0 skipped=0 rescued=0 ignored=0 \\nokd-node-1 : ok=2 changed=2 unreachable=0 failed=0 skipped=0 rescued=0 ignored=0 \\n\\nSat Aug 24 19:33:55 UTC 2019 - Creation of Cloud Provider Config (azure.conf) completed on all nodes successfully\\nSat Aug 24 19:33:55 UTC 2019 - Running Prerequisites via Ansible Playbook\\nFATAL: Current Ansible version (2.8.4) is not supported. Supported versions: 2.4.3.0 or newer but less than 2.8.0\\n\\n[stderr]\\n % Total % Received % Xferd Average Speed Time Time Time Current\\n Dload Upload Total Spent Left Speed\\n\\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\\r100 10 100 10 0 0 1500 0 --:--:-- --:--:-- --:--:-- 1666\\n [WARNING]: provided hosts list is empty, only localhost is available. Note\\nthat the implicit localhost does not match 'all'\\n\\\".\"\r\n }\r\n ]\r\n }\r\n}"}]}

From the error it is clear that the ansible version 2.8.4 is not supported.as we can see that in the masterPrep.sh script file the latest ansible is installed.

any ideas on how i can solve the error.

**Comment by johnsonhays** [comment]
Hi,

I am trying to deploy 3.9.  Getting the same error as well.  Is there a fix for this issue?

Deployment failed. Correlation ID: a62e8c5d-5d71-4df2-ab02-34de9e041ed9. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "Conflict",
            "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'deployOpenShift'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=2\\n[stdout]\\n*******************************\\nok: [localhost]\\n\\nTASK [Evaluate oo_new_etcd_to_config] ******************************************\\n\\nTASK [Evaluate oo_masters_to_config] *******************************************\\nok: [localhost] => (item=hc-okd-master-0)\\nok: [localhost] => (item=hc-okd-master-1)\\nok: [localhost] => (item=hc-okd-master-2)\\n\\nTASK [Evaluate oo_etcd_to_config] **********************************************\\nok: [localhost] => (item=hc-okd-master-0)\\nok: [localhost] => (item=hc-okd-master-1)\\nok: [localhost] => (item=hc-okd-master-2)\\n\\nTASK [Evaluate oo_first_etcd] **************************************************\\nok: [localhost]\\n\\nTASK [Evaluate oo_etcd_hosts_to_upgrade] ***************************************\\nok: [localhost] => (item=hc-okd-master-0)\\nok: [localhost] => (item=hc-okd-master-1)\\nok: [localhost] => (item=hc-okd-master-2)\\n\\nTASK [Evaluate oo_etcd_hosts_to_backup] ****************************************\\nok: [localhost] => (item=hc-okd-master-0)\\nok: [localhost] => (item=hc-okd-master-1)\\nok: [localhost] => (item=hc-okd-master-2)\\n\\nTASK [Evaluate oo_nodes_to_config] *********************************************\\nok: [localhost] => (item=hc-okd-master-0)\\nok: [localhost] => (item=hc-okd-master-1)\\nok: [localhost] => (item=hc-okd-master-2)\\nok: [localhost] => (item=hc-okd-infra-0)\\nok: [localhost] => (item=hc-okd-infra-1)\\nok: [localhost] => (item=hc-okd-node-0)\\nok: [localhost] => (item=hc-okd-node-1)\\n\\nTASK [Add master to oo_nodes_to_config] ****************************************\\n\\nTASK [Evaluate oo_lb_to_config] ************************************************\\n\\nTASK [Evaluate oo_nfs_to_config] ***********************************************\\n\\nTASK [Evaluate oo_glusterfs_to_config] *****************************************\\n\\nTASK [Evaluate oo_etcd_to_migrate] *********************************************\\nok: [localhost] => (item=hc-okd-master-0)\\nok: [localhost] => (item=hc-okd-master-1)\\nok: [localhost] => (item=hc-okd-master-2)\\n\\nPLAY [Install and configure NetworkManager] ************************************\\n\\nTASK [Gathering Facts] *********************************************************\\nok: [hc-okd-master-2]\\nok: [hc-okd-infra-0]\\nok: [hc-okd-node-1]\\nfatal: [hc-okd-master-1]: FAILED! => {\\\"msg\\\": \\\"Timeout (12s) waiting for privilege escalation prompt: \\\"}\\nfatal: [hc-okd-infra-1]: FAILED! => {\\\"msg\\\": \\\"Timeout (12s) waiting for privilege escalation prompt: \\\"}\\nfatal: [hc-okd-master-0]: FAILED! => {\\\"msg\\\": \\\"Timeout (12s) waiting for privilege escalation prompt: \\\"}\\nfatal: [hc-okd-node-0]: FAILED! => {\\\"msg\\\": \\\"Timeout (12s) waiting for privilege escalation prompt: \\\"}\\n\\nTASK [install NetworkManager] **************************************************\\nok: [hc-okd-infra-0]\\nok: [hc-okd-master-2]\\nok: [hc-okd-node-1]\\n\\nTASK [configure NetworkManager] ************************************************\\nchanged: [hc-okd-infra-0] => (item=USE_PEERDNS)\\nchanged: [hc-okd-master-2] => (item=USE_PEERDNS)\\nchanged: [hc-okd-node-1] => (item=USE_PEERDNS)\\nchanged: [hc-okd-master-2] => (item=NM_CONTROLLED)\\nchanged: [hc-okd-infra-0] => (item=NM_CONTROLLED)\\nchanged: [hc-okd-node-1] => (item=NM_CONTROLLED)\\n\\nTASK [enable and start NetworkManager] *****************************************\\nok: [hc-okd-master-2]\\nok: [hc-okd-infra-0]\\nok: [hc-okd-node-1]\\n\\tto retry, use: --limit @/home/clusteradmin/openshift-ansible/playbooks/openshift-node/network_manager.retry\\n\\nPLAY RECAP *********************************************************************\\nhc-okd-infra-0             : ok=4    changed=1    unreachable=0    failed=0   \\nhc-okd-infra-1             : ok=0    changed=0    unreachable=0    failed=1   \\nhc-okd-master-0            : ok=0    changed=0    unreachable=0    failed=1   \\nhc-okd-master-1            : ok=0    changed=0    unreachable=0    failed=1   \\nhc-okd-master-2            : ok=4    changed=1    unreachable=0    failed=0   \\nhc-okd-node-0              : ok=0    changed=0    unreachable=0    failed=1   \\nhc-okd-node-1              : ok=4    changed=1    unreachable=0    failed=0   \\nlocalhost                  : ok=11   changed=0    unreachable=0    failed=0   \\n\\n\\n[stderr]\\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\\n                                 Dload  Upload   Total   Spent    Left  Speed\\n\\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\\r100     6  100     6    0     0    643      0 --:--:-- --:--:-- --:--:--   666\\n [WARNING]: provided hosts list is empty, only localhost is available. Note\\nthat the implicit localhost does not match 'all'\\n\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}

**Comment by satya2048** [comment]
Hi john can you show me the parameters file

**Comment by johnsonhays** [comment]
Hi,

Thanks for your reply.  Here is my parameter file:

{
                "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
                "contentVersion": "1.0.0.0",
                "parameters": {
                                "masterVmSize": {
                                                "value": "Standard_E2s_v3"
                                },
                                "infraVmSize": {
                                                "value": "Standard_E2s_v3"
                                },
                                "nodeVmSize": {
                                                "value": "Standard_E2s_v3"
                                },
                                "storageKind": {
                                                "value": "managed"
                                },
                                "openshiftClusterPrefix": {
                                                "value": "HC-okd"
                                },
                                "masterInstanceCount": {
                                                "value": 3
                                },
                                "infraInstanceCount": {
                                                "value": 2
                                },
                                "nodeInstanceCount": {
                                                "value": 2
                                },
                                "dataDiskSize": {
                                                "value": 128
                                },
                                "adminUsername": {
                                                "value": "clusteradmin"
                                },
                                "openshiftPassword": {
                                                "value": "xxxxxxxxxxxxxxxxxxxxxxxx"
                                },
                                "sshPublicKey": {
                                                "value": "ssh-rsxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                                },
                                "enableMetrics": {
                                                "value": "true"
                                },
                                "enableLogging": {
                                                "value": "false"
                                },
                                "keyVaultResourceGroup": {
                                                "value": "keyvaultrgHC"
                                },
                                "keyVaultName": {
                                                "value": "OKDkeyvaultHC"
                                },
                                "keyVaultSecret": {
                                                "value": "xxxxxxxxxxxxxxxx"
                                },
                                "enableAzure": {
                                                "value": "true"
                                },
                                "aadClientId": {
                                                "value": "xxxxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxxxxxxx"
                                },
                                "aadClientSecret": {
                                                "value": "xxxxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxxxxxxx"
                                },
                                "defaultSubDomainType": {
                                                "value": "nipio"
                                }
                }
}

**Comment by satya2048** [comment]
Hi john can you paste the public key in a single line and try.so that there will be no new line spaces appended.let me know if that works

**Comment by BorisB2015** [comment]
General guidance on how to troubleshoot these issues is described here: https://github.com/microsoft/openshift-origin/#troubleshooting

In short, extension failure tells me 2 things: 1) infrastructure deployment likely succeeded,, 2) the playbook to deploy and configure the cluster has failed. 

Next step is to 1) get ansible logs from the machine; 2) determine the cause of the error; 3) correct the issue and redeploy. If this is the first time deployment, I personally recommend redeploying to a clean environment (rather than incremental) to avoid additional issues. 

Because many different errors manifest themselves in a similar way (extension error), one needs to get on the machine where it runs (ssh on port 2200 with your provided credentials) and look through the output. 

For this particular issue, the first error pointed to an unsupported version of Anisible while the second error  "Timeout (12s) waiting for privilege escalation prompt" makes me think that the private ssh key provided may be password protected.  So when deploying machine connects to other VMs in the cluster it waits for the password to be typed in an unattended environment and hence eventually fails. This would be the next thing to check for. @johnsonhays - please check for this.

Thanks,
Boris.

**Comment by BorisB2015** [comment]
Please reopen with specifics as needed. Thanks!

**Comment by johnsonhays** [comment]
similar issue to Failed to deploy release 3.9: make sure /etc/origin/cloudprovider exists error #111  which is open

**Comment by agrajm** [comment]
Hi @BorisB2015 @haroldwongms 
I'm also getting the "**Timeout (12s) waiting for privilege escalation prompt**" issue and I can confirm that the private ssh key is **Not** password protected. Also this happens more frequently as I increase the number of application nodes from 2 to 10. With the default 2 application nodes, I get this error intermittently. Logging and metrics are not enabled currently to reduce complexity.
Ques - How and where do I increase the timeout from 12s to something significant if that can help here ? 

After logging onto master and doing 
``` ansible -m ping all ``` 
I can see all infra and app nodes reachable. How can I re-run the steps in deployOpenshift.sh now to ensure the right setup ? 
I tried with 
```  ansible-playbook ./updateansiblecfg.yaml  ```
but does not look like its working. 
Any help is appreciated

**Comment by smereczynski** [comment]
I noticed that on larger VM sizes it is not happening.

**Comment by agrajm** [comment]
Hi @smereczynski which VM series did you try this with ?

**Comment by smereczynski** [comment]
Dsv3 or Esv3 I think. With less than 8 vCPU per Node It was hard to not get an error.

**Comment by agrajm** [comment]
@smereczynski  Hmm I just tried with E16v3 (16vCPU, 128 GB Ram) and it still fails. Can you share your paramaters file if possible ?

**Comment by agrajm** [comment]
**Question** - How can we upgrade or downgrade the version of ansible used in this playbooks.... just by switching from 3.9 release of https://github.com/openshift/openshift-ansible/ to another version? 
I think the 12ms timeout is configured in ansible [here ](https://github.com/ceph/ceph-ansible/pull/1860)- and changing to 30 or something similar should resolve this. 
Thoughts ? @BorisB2015 @haroldwongms

**Comment by agrajm** [comment]
Update - Created a [Pull Request ](https://github.com/microsoft/openshift-origin/pull/116) for updating the ssh timeout for ansible making the communication between master and other nodes possible even when the slave nodes are slow to bootup.
