### ISSUE TITLE
Failed the deployment with openshift_use_dnsmasq=true

### ISSUE THREAD

**Issue by eekwong** [Microsoft/openshift-origin#13]
By default, `openshift_use_dnsmasq=false` in azureDeploy.sh. However disabling the dnsmasq leads to a DNS resolution problem in alpine based images (musl libc) because of the multiple nameservers in the containers (one is skydns, and the other is the virtual azure 168.63.129.16): https://docs.openshift.org/latest/install_config/install/prerequisites.html#prereq-dns

Setting [openshift_use_dnsmasq=true](url) failed the deployment at the task
```
TASK [openshift_excluder : Detecting Atomic Host Operating System] *************
fatal: [xyz-node-0]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname xyz-node-0: Name or service not known\r\n", "unreachable": true}
```

since the nodes can't talk to each other using the hostname (but IP works). Any workaround? or tweak to the dnsmasq conf.d files , /etc/hosts ? or better, to configure the cluster properly using openshift_use_dnsmasq=true?

I tried to configure the dnsmasq upstream dns to master-node#8053  and it still doesn't work.

**Comment by ryannix123** [comment]
Was this a recent change? My deployment from a month ago worked.

**Comment by eekwong** [comment]
Not sure, maybe the difference between 1.5 and 1.5.1 OpenShift? or changes in the Azure backend side ... I just started exploring OpenShift in Azure recently.

Can anyone try the openshift_use_dnsmasq=true (in both master/node) and report the result if available? Thanks.

**Comment by leogr** [comment]
Same issue for me. 

Any news?

**Comment by eekwong** [comment]
No updates from me, but i saw two more forks trying out the dnsmasq, which is a better sign.

**Comment by jreypo** [comment]
Tested with `openshift_use_dnsmasq=True` and the deployment finish correctly. I've opened a PR #16 to fix this, waiting for the comments or merge from repo owner.

**Comment by leogr** [comment]
@jreypo Did it not work because `true` instead of `True`?

**Comment by jreypo** [comment]
@leogr Actually my tests were with `true`, in theory it shouldn't matter . Have another branch with all the links pointing to the scripts in my repo instead of Microsoft ones https://github.com/jreypo/openshift-origin/tree/dnsmasq-test I used this to successfully spin up an Origin cluster on my Azure subscription

**Comment by leogr** [comment]
I did the same test some days ago (just setting `openshift_use_dnsmasq=true` [in the same way you did](https://github.com/jreypo/openshift-origin/commit/5af703961ff08c6e66580496e1c0aea29898255e)), but no lock. 
Deployment have failed as described in this issue.
I'll try again.

**Comment by EppO** [comment]
I used @jreypo's fix branch (https://raw.githubusercontent.com/jreypo/openshift-origin/dnsmasq-fix/) in the artifacts location of the template and the deployment did succeed. 
However, I think the dnsmasq setup is wrong, I couldn't resolve any DNS entries in the `.cluster.local` domain inside the containers:
- `/etc/dnsmasq.d/node-dnsmasq.conf` contained: 
```
server=/in-addr.arpa/127.0.0.1
server=/cluster.local/127.0.0.1
```
whereas nothing is listening to the loopback interface and port 53 (dnsmasq binds the host eth0 interface)
```
# netstat -naput | grep ":53 "
tcp        0      0 10.2.0.5:53             0.0.0.0:*               LISTEN      14541/dnsmasq
udp        0      0 10.2.0.5:53             0.0.0.0:*                           14541/dnsmasq
```
- as a result, inside the container:
```
sh-4.2$ ping redis                                                                                                                                                     
^[[Zping: redis: Name or service not known
```

Here are the steps I used to fix the DNS requests inside the containers:

1. looking at the kubernetes DNS service IP address: 
```
# oc get service kubernetes
NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)                 AGE
kubernetes   172.30.0.1   <none>        443/TCP,53/UDP,53/TCP   6h
```
2. I edited `/etc/origin/node/node-dnsmasq.conf` like this (**NOT `/etc/dnsmasq.d/node-dnsmasq.conf`!!!** the latter is generated with the content of the former):
```
server=/in-addr.arpa/172.30.0.1
server=/cluster.local/172.30.0.1
```
3. Surprisingly, it didn't help. `/etc/dnsmasq.d/node-dnsmasq.conf` was properly generated with the correct values but looking at the dnsmasq logs after a restart, I could see it was not using the new values:
```
Jul 13 10:58:55 openshift-node-2 dnsmasq[14541]: setting upstream servers from DBus
Jul 13 10:58:55 openshift-node-2 dnsmasq[14541]: using nameserver 127.0.0.1#53 for domain cluster.local
Jul 13 10:58:55 openshift-node-2 dnsmasq[14541]: using nameserver 127.0.0.1#53 for domain in-addr.arpa
```
4. I had to also edit `/etc/systemd/system/origin-node.service` that contained the 127.0.0.1 references for the domains managed by dnsmasq
- I replaced
```
ExecStartPre=/usr/bin/dbus-send --system --dest=uk.org.thekelleys.dnsmasq /uk/org/thekelleys/dnsmasq uk.org.thekelleys.SetDomainServers array:string:/in-addr.arpa/127.0.0.1,/cluster.local/127.0.0.1
```
- with
```
ExecStartPre=/usr/bin/dbus-send --system --dest=uk.org.thekelleys.dnsmasq /uk/org/thekelleys/dnsmasq uk.org.thekelleys.SetDomainServers array:string:/in-addr.arpa/172.30.0.1,/cluster.local/172.30.0.1
```
I edited these files and restarted NetworkManager and dnsmasq services on all my nodes, and now inside a container:
```
# ping redis                                                                                                                                                     
PING redis.test-project.svc.cluster.local (172.30.251.45) 56(84) bytes of data.
```
I only fixed the DNS requests inside the containers though, my hosts `/etc/resolv.conf` is using only the DNS server of Azure, I'm not yet sure if I need to change that as it doesn't prevent anything to work as far as I can tell.

Hope that helps

**Comment by BastiOfBerlin** [comment]
Hi,

just for the records: I was able to deploy the template after @haroldwongms commited f85a8a8 (Set use_dnsmasq=True).

BR

**Comment by haroldwongms** [comment]
First, sorry for not being active on responding to issues.

It seems the CentOS image from the marketplace does not use Network Manager so that was causing issues with DNS in containers - this is evident in the latest release of 3.6.  In the latest updates to the templates and scripts, I am re-enabling Network Manager so the DNS issue goes away.  

I am closing this issue as the latest changes should be merged shortly after Boris gets a chance to review.

Thank you.

Harold
