### ISSUE TITLE
deployment is failing with error 127

### ISSUE THREAD

**Issue by Aslamlatheef** [Microsoft/openshift-origin#20]
can you please help me the same.

{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "Conflict",
            "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'deployOpenShift'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=127\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}

**Comment by haroldwongms** [comment]
I'm not 100% sure what this issue is related to.  Boris and I are working to release the latest templates and scripts to install Origin 3.6.  Once that goes live, can you please test again?  Thank you.

Harold

**Comment by Aslamlatheef** [comment]
Sure, can i deploy and test now??

Sent from my iPhone

On 16-Sep-2017, at 5:20 AM, Harold Wong <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not 100% sure what this issue is related to. Boris and I are working to release the latest templates and scripts to install Origin 3.6. Once that goes live, can you please test again? Thank you.

Harold

**Comment by haroldwongms** [comment]
Yes, please do.  Thank you.

**Comment by Aslamlatheef** [comment]
I still see this issue


New password:
BAD PASSWORD: The password contains less than 1 non-alphanumeric characters
Retype new password:
passwd: all authentication tokens updated successfully.
[ocpadmin@aacl-master-0 ~]$ su
Password:
[root@aacl-master-0 ocpadmin]#
[root@aacl-master-0 ocpadmin]#
[root@aacl-master-0 ocpadmin]# tail /var/lib/waagent/custom-script/download/1/st                                         derr
 [WARNING]: provided hosts list is empty, only localhost is available
[root@aacl-master-0 ocpadmin]# tail /var/lib/waagent/custom-script/download/1/st                                         dout
TASK [Evaluate groups - g_glusterfs_hosts required] ****************************
skipping: [localhost]

TASK [Evaluate groups - Fail if no etcd hosts group is defined] ****************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Runnin 


---------------------------------------------------------------------------
Azure Event 

"code": "Conflict",
            "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'deployOpenShift'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=2\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}

**Comment by Aslamlatheef** [comment]
when I manual trigger networking then I get this message
 Fail if no etcd hosts group is defined] *********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Running etcd as an embedded service is no longer supported. If this is a new install please define an 'etcd' group with either one or three hosts. These hosts may be the same hosts as your masters. If this is an upgrade you may set openshift_master_unsupported_embedded_etcd=true until a migration playbook becomes available.\n"}
        to retry, use: --limit @/home/ocpadmin/openshift-ansible/playbooks/byo/openshift-node/network_manager.retry

PLAY RECAP **************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1

**Comment by haroldwongms** [comment]
Are you sure you are using the correct branch?  The current template is specifying etcd so that should not be an error.

**Comment by tyayers** [comment]
I am also trying to deploy and get the same error as above ("message": "VM has reported a failure when processing extension 'deployOpenShift'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=2\".")

**Comment by BorisB2015** [comment]
@Aslamlatheef - looking at the errors. @tyayers - please see Troubleshooting section on how to get more details. You are likely hitting the same error.

**Comment by Aslamlatheef** [comment]
its working fine for me after new script

**Comment by BorisB2015** [comment]
The deployment should now work. Please check.
