### ISSUE TITLE
deployment fails due to missing network ansible config

### ISSUE THREAD

**Issue by ivanthelad** [Microsoft/openshift-origin#27]
The deployment of openshift fails when vip  service and pod network configs and not provided 

'########################################################
  1. Hosts:    combank-infra-0, combank-infra-1, combank-master-0, combank-master-1, combank-master-2, combank-node-0
     Play:     Initialize host facts
     Task:     openshift_sanitize_inventory : assert
     Message:  osm_cluster_network_cidr, osm_host_subnet_length, and openshift_portal_net are required inventory variables. If you are upgrading or scaling up these variables should match what is currently used in the cluster. If you don't remember what these values are you can find them in /etc/origin/master/master-config.yaml on a master with the names clusterNetworkCIDR (osm_cluster_network_cidr), hostSubnetLength (osm_host_subnet_length), and serviceNetworkCIDR (openshift_portal_net).

**Comment by Aslamlatheef** [comment]
seems like CIDR block is not amended properly in Json.! check the template and amend before deployment.

**Comment by ivanthelad** [comment]
can you elaborate on what you mean here. cidr block is not amended or set by either the azuertemplate or the template params. by default ansible has defaults set defaults.  you should not need  set these. 
most likely you are been effected by this recent bug in origin ansible. https://github.com/openshift/openshift-ansible/issues/5448

**Comment by BorisB2015** [comment]
Please reopen if this is still applicable. Thanks!
