### ISSUE TITLE
deployOpenShift fails with msg: Running etcd as an embedded service is no longer supported.

### ISSUE THREAD

**Issue by pascals-msft** [Microsoft/openshift-origin#30]
From /var/lib/waagent/custom-script/download/1/stdout on the master-0 VM:

TASK [Evaluate groups - Fail if no etcd hosts group is defined] ****************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Running etcd as an embedded service is no longer supported. If this is a new install please define an 'etcd' group with either one or three hosts. These hosts may be the same hosts as your masters. If this is an upgrade you may set openshift_master_unsupported_embedded_etcd=true until a migration playbook becomes available.\n"}
        to retry, use: --limit @/home/azureuser/openshift-ansible/playbooks/byo/openshift-node/network_manager.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1

Thanks!

**Comment by ivanthelad** [comment]
could you provide details regarding your template deployment parameters

**Comment by pascals-msft** [comment]
My parameters (with some '******' where needed)

Thank!

{
	"$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
	"contentVersion": "1.0.0.0",
	"parameters": {
		"_artifactsLocation": {
			"value": "https://raw.githubusercontent.com/Microsoft/openshift-origin/master/"
		},
		"masterVmSize": {
			"value": "Standard_DS2_v2"
		},
		"infraVmSize": {
			"value": "Standard_DS2_v2"
		},
		"nodeVmSize": {
			"value": "Standard_DS2_v2"
		},
		"openshiftClusterPrefix": {
			"value": "demo"
		},
		"masterInstanceCount": {
			"value": 2
		},
		"infraInstanceCount": {
			"value": 2
		},
		"nodeInstanceCount": {
			"value": 1
		},
		"dataDiskSize": {
			"value": 128
		},
		"adminUsername": {
			"value": "azureuser"
		},
		"openshiftPassword": {
			"value": "********"
		},
		"sshPublicKey": {
			"value": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQ********Gg1GL1wzWrQiiWhXn"
		},
		"keyVaultResourceGroup": {
			"value": "demo-openshift"
		},
		"keyVaultName": {
			"value": "demo-openshift-kv"
		},
		"keyVaultSecret": {
			"value": "demosshkey"
		},
		"aadClientId": {
			"value": "3b6dc805-d297-4a7e-a502-fb4b29948c87"
		},
		"aadClientSecret": {
			"value": "********"
		},
		"defaultSubDomainType": {
			"value": "xipio"
		},
		"defaultSubDomain": {
			"value": "changeme"
		}
	}
}

**Comment by pascals-msft** [comment]
My parameters, with some XXXXX where needed:
Thanks!

{
	"$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
	"contentVersion": "1.0.0.0",
	"parameters": {
		"_artifactsLocation": {
			"value": "https://raw.githubusercontent.com/Microsoft/openshift-origin/master/"
		},
		"masterVmSize": {
			"value": "Standard_DS2_v2"
		},
		"infraVmSize": {
			"value": "Standard_DS2_v2"
		},
		"nodeVmSize": {
			"value": "Standard_DS2_v2"
		},
		"openshiftClusterPrefix": {
			"value": "demo"
		},
		"masterInstanceCount": {
			"value": 2
		},
		"infraInstanceCount": {
			"value": 2
		},
		"nodeInstanceCount": {
			"value": 1
		},
		"dataDiskSize": {
			"value": 128
		},
		"adminUsername": {
			"value": "azureuser"
		},
		"openshiftPassword": {
			"value": "XXXXXXXXXX"
		},
		"sshPublicKey": {
			"value": "ssh-rsa AAAAB3NzaC1yc2EAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXzWrQiiWhXn"
		},
		"keyVaultResourceGroup": {
			"value": "demo-openshift"
		},
		"keyVaultName": {
			"value": "demo-openshift-kv"
		},
		"keyVaultSecret": {
			"value": "demosshkey"
		},
		"aadClientId": {
			"value": "3b6dc805-d297-4a7e-a502-fb4b29948c87"
		},
		"aadClientSecret": {
			"value": "XXXXXXXXXX"
		},
		"defaultSubDomainType": {
			"value": "xipio"
		},
		"defaultSubDomain": {
			"value": "changeme"
		}
	}
}

**Comment by ivanthelad** [comment]
Change masterInstanceCount to 3 and rerun

**Comment by ivanthelad** [comment]
most likely related to https://github.com/Microsoft/openshift-origin/issues/31

**Comment by pascals-msft** [comment]
Thanks Ivan, it seems to make sense. Trying right now with 3 masters.

**Comment by pascals-msft** [comment]
Thanks Ivan, the deployment succeded:

$ az group deployment list -g demo-openshift-1
Name                 Timestamp                         State
-------------------  --------------------------------  ---------
masterVmDeployment2  2017-09-21T21:42:40.579625+00:00  Succeeded
infraVmDeployment1   2017-09-21T21:42:42.687155+00:00  Succeeded
nodeVmDeployment0    2017-09-21T21:42:44.924933+00:00  Succeeded
infraVmDeployment0   2017-09-21T21:42:53.848872+00:00  Succeeded
masterVmDeployment1  2017-09-21T21:42:55.600605+00:00  Succeeded
masterVmDeployment0  2017-09-21T21:42:59.109905+00:00  Succeeded
OpenShiftDeployment  2017-09-21T22:17:55.188055+00:00  Succeeded
azuredeploy          2017-09-21T22:17:59.279237+00:00  Succeeded

**Comment by BorisB2015** [comment]
This should now work as expected! Template updated. Thanks Ivan!

**Comment by vguaglione** [comment]
This is odd... I'm also receiving this same error when attempting to add the Prometheus component to an existing, running openshift 3.9 cluster.  I'm running the playbooks/openshift-prometheus/config.yml standard Redhat playbook with a basic inventory file specifying only:

openshift_prometheus_namespace=openshift-metrics
openshift_prometheus_node_selector={"region":"infra"}

Pretty simple.  This error makes no sense.  Can someone provide guidance, please?
