### ISSUE TITLE
Allow values for masterInstanceCount should be [1,3,5] and not [2,3]

### ISSUE THREAD

**Issue by ivanthelad** [Microsoft/openshift-origin#31]
https://github.com/Microsoft/openshift-origin/blob/master/azuredeploy.json#L97

as etcd requires a quorm to run and is deployed by default in this template on the same machines as the controller and api (masters). the current values of (2,3) does not make sense. the cluster will fail with a master count of 2 (or probably wont deploy )

Only 1,3,5 are valid counts for the master

**Comment by BorisB2015** [comment]
Thanks @ivanthelad for pointing this out! This seems to be what me and others have hit after the recent update. Checking if no other issues are showing up and one of us will update the template.

**Comment by BorisB2015** [comment]
This should now work as expected. Template updated. Thanks!
