### ISSUE TITLE
Azure CLI 2.0 fails because of UTF-8 BOM in the template

### ISSUE THREAD

**Issue by pascals-msft** [Microsoft/openshift-origin#34]
I'm using az version 2.0.17 from Ubuntu 16.04 and the deployment fails instantly when using the template URI:

$ az group deployment create -g demo-3 -n azuredeploy --template-uri https://raw.githubusercontent.com/Microsoft/openshift-origin/master/azuredeploy.json --parameters @azuredeploy.parameters.demo-3.json -o json
Deployment failed. Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

It works fine if I wget the template, remove the UTF-8 BOM and use the --template-file parameter.

**Comment by haroldwongms** [comment]
Not sure how this happened.  I just opened a PR  (https://github.com/Microsoft/openshift-origin/pull/36) to correct the 4 files that were using UTF-8 BOM

**Comment by BorisB2015** [comment]
Should be fixed by https://github.com/Microsoft/openshift-origin/pull/36
