### ISSUE TITLE
Openshift deployment steps keeps failing on the same step

### ISSUE THREAD

**Issue by nielsvanderbeke** [Microsoft/openshift-origin#40]
After executing the deplyment it allways fails at the same step without extra info.

{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "Conflict",
            "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'deployOpenShift'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=2\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}

**Comment by BorisB2015** [comment]
@nielsvanderbeke - please take a look at the [troubleshooting section](https://github.com/Microsoft/openshift-origin#troubleshooting) and get additional details on the failure.

Specifically you need to login to master (get IP from the deployment and use port 2200 and the private key you have created/provided in the prep steps) and look at the log. It will tell you exactly what went wrong during the deployment.

Post your findings here. Thanks!

**Comment by HoogWater** [comment]
i am getting the same error, after looking at the logs on the first master i see the following 2 error

in the stdout log for the deployOpenshift.sh (ansible handler)
> RUNNING HANDLER [restart origin-node] "msg": "Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See \"systemctl status origin-node.service\" and \"journalctl -xe\" for details.\n"}

in the systemctl status for origin-node
> 122683 kubelet_node_status.go:73] Unable to construct v1.Node object for kubelet: failed to get external ID from cloud provider: compute.VirtualMachinesClient#Get: Failure res...e returned an error

also in the journalctl for 

> origin-master-controllers E1009 13:50:13.256815  121957 nodecontroller.go:757] Error determining if node myorigin-master-1 exists in cloud: compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=403 -- Original

> atomic-openshift-master-api[121857]: I1009 13:52:50.522515  121857 logs.go:41] http: TLS handshake error from ....:56749: EOF

**Comment by haroldwongms** [comment]
@HoogWater If this is occurring in the setup-azure-node.yml playbook, then this tells me you have an issue related to the Service Principal (SP).  Either you specified the wrong information or the SP does not have permissions to the Subscription or Resource Group.

**Comment by BorisB2015** [comment]
@HoogWater - please check 

`az role assignment list --resource-group YourResourceGroupName -o=table`

you should get something like:

```
Principal                     Role         Scope
----------------------------  -----------  ---------------------------------------------------------------------------------------
http://YourAppPrincipalName  Contributor  /subscriptions/GUID/resourceGroups/YourGroupName
```
If you get nothing, do this to assign:

`az role assignment create --assignee Your-App-GUID --resource-group YourResourceGroupName --role Contributor`

Create a new group and assign Contributor role to your app on this group with the last command and then run the deployment to this group.

Let this thread know if it worked. Thanks!

**Comment by BorisB2015** [comment]
Please reopen with specific details if this is still an issue. Thanks!
