### ISSUE TITLE
Unable to SSH into the Master Node 

### ISSUE THREAD

**Issue by tapanbanker** [Microsoft/openshift-origin#41]
Hello Microsoft Open Shift Contributor,

We would like to know the steps on how to SSH into the Open Shift Virtual machine containing the Master Node. We have deployed the Azure ARM Templates provided from your GitHub repository https://github.com/Microsoft/openshift-origin
When attempted to SSH the connection times out, we have checked the ports are open in the Network Security Group.  Can your prompt direction or assistance be provided here? 
 
![image](https://user-images.githubusercontent.com/6992655/31506621-ec645d6e-af45-11e7-9022-1ef9760657ac.png)

**Comment by BorisB2015** [comment]
Please confirm that you are ssh-in on port 2200. See https://github.com/Microsoft/openshift-origin/blob/master/README.md#troubleshooting

**Comment by BorisB2015** [comment]
Please reopen with additional details if necessary.
