### ISSUE TITLE
Core quota

### ISSUE THREAD

**Issue by ryannix123** [Microsoft/openshift-origin#42]
I've filled out the quota increase request several times. However, despite the approval for more (105), I keep getting this error:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"error\": {\r\n    \"code\": \"OperationNotAllowed\",\r\n    \"message\": \"Operation results in exceeding quota limits of Core. Maximum allowed: 10, Current in use: 10, Additional requested: 2. Please read more about quota increase at http://aka.ms/corequotaincrease.\"\r\n  }\r\n}"}]}

How many cores do I need for the default options in the deployment script?

		"masterVmSize": {
			"value": "Standard_DS2_v2"
		},
		"infraVmSize": {
			"value": "Standard_DS2_v2"
		},
		"nodeVmSize": {
			"value": "Standard_DS2_v2"
		},

**Comment by BorisB2015** [comment]
@ryannix123: use something like `az vm list-usage --location WestUS` to check how many cores you are using in a given region. Quotas may be different per region. You can run this in Cloud Shell and check that you are in the correct subscription if you have several.

How many required: DS2 machines (https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-general) are 2-core VMs. In sample parameter file we have 3 masters, 2 infra nodes and 1 regular node. That would need 6 VMs x 2 cores = 12 cores which is what you have in the excerpt above.

Current config is made 3 masters only which brings the minimum required core count higher. 

@haroldwongms: we should consider size that would fit into 10 cores or less. Possibly as separate template.

**Comment by ryannix123** [comment]
Thanks, Boris. Currently I'm using 0 cores in any region because this is the only thing I'm trying to deploy so far. I put in a request to increase my quota to an arbitrary 105 but I'm not getting failures on deployment.

**Comment by ryannix123** [comment]
Turns out it was quota increase request for the wrong region. i.e. northcentral vs central.

**Comment by BorisB2015** [comment]
I'm assuming we can close this. Please reopen if necessary.
