### ISSUE TITLE
Opehshift Origin Installation fails on Azure

### ISSUE THREAD

**Issue by amitabh-nayak** [Microsoft/openshift-origin#45]
Azure Support Ticket ref : 117102716568998

I am installing Openshift Container. following the instructions provided at link https://docs.microsoft.com/en-us/azure/virtual-machines/linux/openshift-origin. The installation is failing with the below error message:  
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'deployOpenShift'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=2\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"}]}

Then I created the two VMs on Azure manually. Configured  the master and node vm as per the document. I ran the Ansible inventory file and playbook. It failed with message below:  
fatal: [localhost]: FAILED! => {'changed': false, 'failed': true, 'msg': 'Running etcd as an embedded service is no longer supported. If this is a new install please define an 'etcd' group with either one or three hosts. These hosts may be the same hosts as your masters. If this is an upgrade you may set openshift_master_unsupported_embedded_etcd=true until a migration playbook becomes available.\\n'}
to retry, use: --limit @/root/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost : ok=1 changed=0 unreachable=0 failed=1 

Failure summary:

1. Hosts: localhost
Play: Populate config host groups
Task: Evaluate groups - Fail if no etcd hosts group is defined
Message: Running etcd as an embedded service is no longer supported. If this is a new install please define an 'etcd' group with either one or three hosts. These hosts may be the same hosts as your masters. If this is an upgrade you may set openshift_master_unsupported_embedded_etcd=true until a migration playbook becomes available.
Attached my playbook file
[ANSIBLE_HOST.txt](https://github.com/Microsoft/openshift-origin/files/1432073/ANSIBLE_HOST.txt)

**Comment by haroldwongms** [comment]
This template does not support a single master cluster.  This means you are customizing the template to enable a single master install.  You will also need to modify the hosts file to add a section for [etcd].

**Comment by amitabh-nayak** [comment]
I modified the ANSIBLE_HOST file and added the etcd (embedd
[ANSIBLE_HOST_ETCD.txt](https://github.com/Microsoft/openshift-origin/files/1436094/ANSIBLE_HOST_ETCD.txt)
ing master node)section . Its failing with message "Running etcd as an embedded service is no longer supported" . I checked the openshift-ansible/playbooks/common/openshift-cluster/evaluate_groups.yml file.It has the etcd validation section. I am thinking of creating a VM and install etcd on it. Is this the right approach ? I will greatly appreciate if you could give me some pointers how to do it.

**Comment by haroldwongms** [comment]
I worked with Amitabh to solve his issue.  Part of the problem was a random networking failure.  Closing this issue.
