### ISSUE TITLE
The playbook network_manager.yml could not be found

### ISSUE THREAD

**Issue by erjosito** [Microsoft/openshift-origin#47]
Hi there,

I am deploying the template in West US 2 and getting the following error:

"message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'deployOpenShift'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=1\\n[stdout]\\nSun Dec 10 19:54:33 UTC 2017  - Starting Script\\nSun Dec 10 19:54:33 UTC 2017  - Generating Private keys for use by Ansible for OpenShift Installation\\nSun Dec 10 19:54:33 UTC 2017 - Configuring SSH ControlPath to use shorter path name\\nSun Dec 10 19:54:33 UTC 2017  - Updating ansible.cfg file\\n\\nPLAY [localhost] ***************************************************************\\n\\nTASK [lineinfile] **************************************************************\\nchanged: [localhost]\\n\\nPLAY RECAP *********************************************************************\\nlocalhost                  : ok=1    changed=1    unreachable=0    failed=0   \\n\\nSun Dec 10 19:54:35 UTC 2017  - Create Ansible Playbooks for Post Installation tasks\\nSun Dec 10 19:54:35 UTC 2017  - Create Ansible Hosts file\\nSun Dec 10 19:54:35 UTC 2017  - Cloning openshift-ansible repo for use in installation\\nCloning into '/home/jose/openshift-ansible'...\\nSun Dec 10 19:54:38 UTC 2017  - Running network_manager.yml playbook\\n\\n[stderr]\\n [WARNING]: Could not match supplied host pattern, ignoring: all\\n [WARNING]: provided hosts list is empty, only localhost is available\\nERROR! the playbook: openshift-ansible/playbooks/byo/openshift-node/network_manager.yml could not be found\\n\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"

Any hint?

Thanks!

**Comment by erjosito** [comment]
Looks like network-manager.yml is here:
~/openshift-ansible/playbooks/openshift-node/network_manager.yml

**Comment by erjosito** [comment]
byo/config.yml has been moved as well (../deploy_cluster.yml), and the service broker install seems to break ("oc auth" is issued with the invalid flag -f inside of the playbooks). I changed the path for network_manager.yml and config.yml, and inserted the variable template_service_broker_install=False to control the installation of service broker.

I will send you a pull request with the changes.

Cheers,

**Comment by meeuwesen** [comment]
Hallo Erjosito, can you please tell me which files you have edited to get this working.

Cheers

**Comment by erjosito** [comment]
Hey,

You can have a look at the pull request (https://github.com/Microsoft/openshift-origin/pull/48) to see exactly what I changed. Or you can try to deploy from my fork here: https://github.com/erjosito/openshift-origin

Cheers,
Jose

**Comment by ivanthelad** [comment]
Perhaps we should anchor to a explicit version of origin 
for instance just checkout a release instead of always master 
https://github.com/ivanthelad/openshift-origin/blob/master/scripts/deployOpenShift.sh#L441

**Comment by erjosito** [comment]
I would welcome that, due to the inherent dynamic nature of Origin. Somebody should be continuously (weekly/monthly?) testing the version to link to, so that it does not get too outdated.

**Comment by EppO** [comment]
I addressed this in my fork (#49), cloning the v3.6 branch of openshift-ansible because the current deployment template is compatible only with 3.6 so far.

**Comment by asatsi** [comment]
Hi @erjosito @EppO after making the changes did you again submit the "az group deployment create" job as per Microsoft documentation or you proceeded further manually? Please suggest.

**Comment by haroldwongms** [comment]
This is fixed by cloning to a specific branch (release-3.6 or release-3.7).
