### ISSUE TITLE
Creation of Storage Class yaml in Master-0 fails

### ISSUE THREAD

**Issue by edmacabebe** [Microsoft/openshift-origin#52]
Block scope may have been mistyped. This causes the non-creation of scgeneric1.yml file.

Suggesting 

# Create Storage Class yml files on MASTER-0
if hostname -f|grep -- "-0" >/dev/null
then
cat > /home/${SUDOUSER}/scgeneric1.yml <<EOF
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: generic
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/azure-disk
parameters:
  storageAccount: ${STORAGEACCOUNT1}
  location: ${LOCATION}
EOF
fi 

This is causing the deployOpenshift.sh script in Azure to fail.

**Comment by haroldwongms** [comment]
This should now be fixed.  Please try again and let us know your results.  Thanks.

**Comment by edmacabebe** [comment]
Thanks Harold for the updates. Would appreciate a perfect 3.7 deployment when I attempt to do it again any moment soon.

**Comment by haroldwongms** [comment]
I don't know about "perfect", but hopefully, the deployment will succeed.

**Comment by haroldwongms** [comment]
Closing this issue as it seems it has been corrected.
