### ISSUE TITLE
Add release-3.7 branch to install Origin 3.7 on Azure

### ISSUE THREAD

**Issue by plaimbock** [Microsoft/openshift-origin#53]
Any chance a release-3.7 branch could be added so it's possible to install Origin 3.7 on CentOS 7 on Azure with these templates?

**Comment by ryannix123** [comment]
I'd like to second that request. 👍

**Comment by ivanthelad** [comment]
Hey,
my fork will deploy 3.7 based on centos 
https://github.com/ivanthelad/openshift-origin/blob/master/scripts/deployOpenShift.sh#L372

**Comment by ryannix123** [comment]
Great. Thanks, @ivanthelad!

**Comment by haroldwongms** [comment]
Thanks @ivanthelad!  I will start the work to update to deploy Origin 3.7 and support managed as well as unmanaged disks.  I needed to complete the Container Platform work first - that just went live a few minutes ago.

**Comment by plaimbock** [comment]
Thanks @ivanthelad and @haroldwongms!

**Comment by ivanthelad** [comment]
@haroldwongms done in https://github.com/Microsoft/openshift-origin/pull/55

**Comment by haroldwongms** [comment]
The master branch is now updated to deploy Origin 3.7.  Will continue to work with @ivanthelad to improve and enhance - along with anyone else who is willing to help.

**Comment by edmacabebe** [comment]
A 3:2:1 deployment on ds3 VM worked like a charm without much of glitch, nor me having to intervene going inside VM-0 for some remedial action.

**Comment by haroldwongms** [comment]
master is now deploying 3.7 and we also now have a release-3.7 branch.  Closing issue.
