### ISSUE TITLE
branch 3.6 does not allow a single master. and outline [3,5] as the only viable values

### ISSUE THREAD

**Issue by ivanthelad** [Microsoft/openshift-origin#61]
It should be possible to allow vaules [1,3,5]
kinda related to the following closed bug
https://github.com/Microsoft/openshift-origin/issues/31

**Comment by haroldwongms** [comment]
3.9 now supports a single master.  This is in master branch as well as release-3.9 branch.  

No plans to backport to 3.7 or 3.6 at this time.

**Comment by haroldwongms** [comment]
I have backported a single master to release-3.7 branch as well.  Since 3.6 is now a little outdated, I don't plan to update that release branch.

**Comment by haroldwongms** [comment]
Closing as 3.9 and newer supports a single master.
