### ISSUE TITLE
Kube Nodes NotReady Status and are stuck

### ISSUE THREAD

**Issue by edmacabebe** [Microsoft/openshift-origin#62]
I configured my deployment template with 3 masters, 2 infra and 3 nodes. I disabled metrics, logging, and cockpit for the time-being. Set azure as the provider, and the storage disks to managed. I'm using the master branch, hence, the OS is v3.7. I chose Standard_DS3_v2s as my VM.
After about less that an hour, it seems like all was a successfully provisioned and deployed. I checked the Openshift, and the default namespace and it's built-in DTRegistry, and console seems to be working. But using the OS CLI, checking the oc get nodes, to my dismay, all nodes have a "Not Ready" status! 
Actually, I discovered this only when I attempted to deploy my project's namespace. They're all failing to some degree, where resources can't be scheduled says monitored event logs.
I suspect that a bug is occurring somewhere at the resource allocation side of Azure. The journalctl logs says something like about an issue with the adal. Not certain, but maybe it is with oauth? Not sure why it's needed. A related Azure ticket has been opened for this: SR number 118013017553583

Any insights or possible solution?

**Comment by edmacabebe** [comment]
I followed some issue below and simply disabled azure as cloudprovider, strangely, and finally, the annoying deployment glitch mentioned are gone!

**Comment by heatmiser** [comment]
With Azure cloudprovider enabled, can you post logs from 'systemctl status origin-node.service' and 'journalctl -xe' as the origin-node service is starting?  This should provide some clues as to what is wrong with your Azure configuration as it relates to the cloudprovider configuration.

**Comment by edmacabebe** [comment]
@heatmiser since i've already torn-down that erring non-functioning cluster, I have no chance anymore to try checking the status of the origin-node.service daemon. I was not even aware of it's existence. But I was able to capture a snip of the master's journalctl log during the provisioning window.

Here's the log that I got. I'm hoping someone from the microsoft azure team working for openshift/origin can provide a definitive statement about this event. What is rationale why I need to enableAzure vs disable it as cloudprovider. 

Jan 31 01:42:40 wright-master-0 origin-node[17383]: I0131 01:42:40.983879   17383 kubelet_node_status.go:270] Setting node annotation to enable volume controller attach/detach
Jan 31 01:42:41 wright-master-0 origin-node[17383]: E0131 01:42:41.266931   17383 kubelet_node_status.go:78] Unable to construct v1.Node object for kubelet: failed to get external ID from cloud provider: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/ff6294e2-6c87-4b62-b3a3-aba5e0a17c8d/resourceGroups/INGAsiaOOCP/providers/Microsoft.Compute/virtualMachines/wright-master-0?api-version=2016-04-30-preview: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '400'
Jan 31 01:42:42 wright-master-0 atomic-openshift-master-api[14229]: I0131 01:42:42.381403   14229 logs.go:41] http: TLS handshake error from 168.63.129.16:58933: EOF
Jan 31 01:42:43 wright-master-0 atomic-openshift-master-api[14229]: I0131 01:42:43.718123   14229 rest.go:362] Starting watch for /apis/network.openshift.io/v1/egressnetworkpolicies, rv=6907 labels= fields= timeout=5m13s
Jan 31 01:42:44 wright-master-0 origin-master-controllers[14356]: E0131 01:42:44.908266   14356 nodecontroller.go:678] Error determining if node wright-node-0 exists in cloud: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/ff6294e2-6c87-4b62-b3a3-aba5e0a17c8d/resourceGroups/INGAsiaOOCP/providers/Microsoft.Compute/virtualMachines/wright-node-0?api-version=2016-04-30-preview: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '400'
Jan 31 01:42:45 wright-master-0 origin-master-controllers[14356]: E0131 01:42:45.171350   14356 nodecontroller.go:678] Error determining if node wright-node-1 exists in cloud: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/ff6294e2-6c87-4b62-b3a3-aba5e0a17c8d/resourceGroups/INGAsiaOOCP/providers/Microsoft.Compute/virtualMachines/wright-node-1?api-version=2016-04-30-preview: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '400'
Jan 31 01:42:45 wright-master-0 origin-master-controllers[14356]: E0131 01:42:45.422103   14356 nodecontroller.go:678] Error determining if node wright-infra-0 exists in cloud: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/ff6294e2-6c87-4b62-b3a3-aba5e0a17c8d/resourceGroups/INGAsiaOOCP/providers/Microsoft.Compute/virtualMachines/wright-infra-0?api-version=2016-04-30-preview: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '400'
Jan 31 01:42:45 wright-master-0 origin-master-controllers[14356]: E0131 01:42:45.666051   14356 nodecontroller.go:678] Error determining if node wright-infra-1 exists in cloud: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/ff6294e2-6c87-4b62-b3a3-aba5e0a17c8d/resourceGroups/INGAsiaOOCP/providers/Microsoft.Compute/virtualMachines/wright-infra-1?api-version=2016-04-30-preview: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '400'
Jan 31 01:42:45 wright-master-0 origin-master-controllers[14356]: E0131 01:42:45.905983   14356 nodecontroller.go:678] Error determining if node wright-master-0 exists in cloud: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/ff6294e2-6c87-4b62-b3a3-aba5e0a17c8d/resourceGroups/INGAsiaOOCP/providers/Microsoft.Compute/virtualMachines/wright-master-0?api-version=2016-04-30-preview: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '400'
Jan 31 01:42:46 wright-master-0 origin-master-controllers[14356]: E0131 01:42:46.165782   14356 nodecontroller.go:678] Error determining if node wright-master-1 exists in cloud: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/ff6294e2-6c87-4b62-b3a3-aba5e0a17c8d/resourceGroups/INGAsiaOOCP/providers/Microsoft.Compute/virtualMachines/wright-master-1?api-version=2016-04-30-preview: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '400'
Jan 31 01:42:46 wright-master-0 origin-master-controllers[14356]: E0131 01:42:46.610741   14356 nodecontroller.go:678] Error determining if node wright-master-2 exists in cloud: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/ff6294e2-6c87-4b62-b3a3-aba5e0a17c8d/resourceGroups/INGAsiaOOCP/providers/Microsoft.Compute/virtualMachines/wright-master-2?api-version=2016-04-30-preview: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '400'
Jan 31 01:42:47 wright-master-0 atomic-openshift-master-api[14229]: I0131 01:42:47.381906   14229 logs.go:41] http: TLS handshake error from 168.63.129.16:58984: EOF
Jan 31 01:42:48 wright-master-0 origin-node[17383]: I0131 01:42:48.267342   17383 kubelet_node_status.go:270] Setting node annotation to enable volume controller attach/detach
Jan 31 01:42:48 wright-master-0 origin-node[17383]: E0131 01:42:48.511217   17383 kubelet_node_status.go:78] Unable to construct v1.Node object for kubelet: failed to get external ID from cloud provider: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/ff6294e2-6c87-4b62-b3a3-aba5e0a17c8d/resourceGroups/INGAsiaOOCP/providers/Microsoft.Compute/virtualMachines/wright-master-0?api-version=2016-04-30-preview: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '400'
Jan 31 01:42:50 wright-master-0 atomic-openshift-master-api[14229]: I0131 01:42:50.681484   14229 rest.go:362] Starting watch for /api/v1/replicationcontrollers, rv=7753 labels= fields= timeout=8m0s
Jan 31 01:42:50 wright-master-0 etcd[36447]: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = stream error: stream ID 9; CANCEL")
Jan 31 01:42:50 wright-master-0 atomic-openshift-master-api[14229]: I0131 01:42:50.831150   14229 rest.go:362] Starting watch for /apis/build.openshift.io/v1/builds, rv=6963 labels= fields= timeout=5m10s
Jan 31 01:42:50 wright-master-0 atomic-openshift-master-api[14229]: E0131 01:42:50.843302   14229 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
Jan 31 01:42:50 wright-master-0 etcd[36447]: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = stream error: stream ID 11; CANCEL")
Jan 31 01:42:50 wright-master-0 origin-master-controllers[14356]: W0131 01:42:50.843721   14356 reflector.go:343] github.com/openshift/origin/pkg/build/generated/informers/internalversion/factory.go:45: watch of *build.Build ended with: etcdserver: mvcc: required revision has been compacted
Jan 31 01:42:51 wright-master-0 atomic-openshift-master-api[14229]: I0131 01:42:51.849043   14229 rest.go:362] Starting watch for /apis/build.openshift.io/v1/builds, rv=8857 labels= fields= timeout=9m47s
Jan 31 01:42:51 wright-master-0 origin-master-controllers[14356]: E0131 01:42:51.924672   14356 nodecontroller.go:678] Error determining if node wright-master-2 exists in cloud: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/ff6294e2-6c87-4b62-b3a3-aba5e0a17c8d/resourceGroups/INGAsiaOOCP/providers/Microsoft.Compute/virtualMachines/wright-master-2?api-version=2016-04-30-preview: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '400'
Jan 31 01:42:52 wright-master-0 origin-master-controllers[14356]: E0131 01:42:52.174021   14356 nodecontroller.go:678] Error determining if node wright-node-0 exists in cloud: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/ff6294e2-6c87-4b62-b3a3-aba5e0a17c8d/resourceGroups/INGAsiaOOCP/providers/Microsoft.Compute/virtualMachines/wright-node-0?api-version=2016-04-30-preview: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '400'
Jan 31 01:42:52 wright-master-0 atomic-openshift-master-api[14229]: I0131 01:42:52.382151   14229 logs.go:41] http: TLS handshake error from 168.63.129.16:59013: EOF
Jan 31 01:42:52 wright-master-0 origin-master-controllers[14356]: E0131 01:42:52.421977   14356 nodecontroller.go:678] Error determining if node wright-node-1 exists in cloud: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/ff6294e2-6c87-4b62-b3a3-aba5e0a17c8d/resourceGroups/INGAsiaOOCP/providers/Microsoft.Compute/virtualMachines/wright-node-1?api-version=2016-04-30-preview: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '400'
Jan 31 01:42:52 wright-master-0 origin-master-controllers[14356]: E0131 01:42:52.728076   14356 nodecontroller.go:678] Error determining if node wright-infra-0 exists in cloud: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/ff6294e2-6c87-4b62-b3a3-aba5e0a17c8d/resourceGroups/INGAsiaOOCP/providers/Microsoft.Compute/virtualMachines/wright-infra-0?api-version=2016-04-30-preview: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '400'
Jan 31 01:42:53 wright-master-0 origin-master-controllers[14356]: E0131 01:42:52.990933   14356 nodecontroller.go:678] Error determining if node wright-infra-1 exists in cloud: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/ff6294e2-6c87-4b62-b3a3-aba5e0a17c8d/resourceGroups/INGAsiaOOCP/providers/Microsoft.Compute/virtualMachines/wright-infra-1?api-version=2016-04-30-preview: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '400'
Jan 31 01:42:53 wright-master-0 origin-master-controllers[14356]: E0131 01:42:53.234066   14356 nodecontroller.go:678] Error determining if node wright-master-0 exists in cloud: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/ff6294e2-6c87-4b62-b3a3-aba5e0a17c8d/resourceGroups/INGAsiaOOCP/providers/Microsoft.Compute/virtualMachines/wright-master-0?api-version=2016-04-30-preview: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '400'

**Comment by heatmiser** [comment]
Kubernetes has the concept of a Cloud Provider, which is a module which provides an interface for managing TCP Load Balancers, Nodes (Instances) and Networking Routes for the underlying cloud infrastructure. When Enable Azure is set to true and requisite credentials are supplied, the Origin/OpenShift cluster can interact directly with the Azure control plane, for example utilize Azure disks for persistent storage, etc.

In order to do that, an azure.conf file with necessary Azure credentials (Service Principal config info) needs to be defined on each node in the system, as well as the following modifications:
    - master-config.yaml and node-config.yaml on all master nodes to reference azure.conf and enable azure cloud provider
    - node-config.yaml on all infra and app nodes to reference azure.conf and enable azure cloud provider

Once the above is done, all nodes are deleted from within Kubernetes, so that Kubernetes can then look at it's local config and subsequently contact Azure (utilizing the Service Principal information in azure.conf) to find out "who" it is.  Once it is able to verify that information with Azure, the node gets added back into the cluster.  The errors above seem to indicate a problem with this communication from the node back to Azure.

First thing is to verify your Service Principal (SP) configuration. Make sure that you create a SP and assign it the "Contributor" role.  Once you do, I recommend utilizing the Azure CLI 2.0 to verify that you can login using the SP ID and credentials just created and test read and write capabilities by creating a test resource group, perform a resource group listing and then delete the test resource group.  Please verify this before continuing troubleshooting.

**Comment by edmacabebe** [comment]
I believe my az cli2 service principal creation & deployment script is in accord to your narration... but will certainly make another deployment soon, we'll find out ...
#------------
RG=testRG
LOC=au
SUB="########-####-####-####-###########"
KV="$RG-kv"
SEC="$RG-secret"
#--------------
az account set --subscription=$SUB
az group create -n $RG -l $LOC
az keyvault create -n $KV -g $RG -l $LOC --enabled-for-template-deployment true
az keyvault secret set --vault-name $KV -n $SEC --file ~/.ssh/id_rsa
#--------------
sp_id=$(az ad sp list --display-name $RG-cloudprovider |grep objectId|awk -F\" '{ print $4 }')
if [ "$sp_id" != "" ]
then
  az ad sp delete --id $sp_id
fi
#---------------
az ad sp create-for-rbac -n $RG-cloudprovider --password Pass@word1 --role contributor --scopes="/subscriptions/########-####-####-####-###########/resourceGroups/$RG"
#---do manual or auto-injection of vars like tenantid into the local arm template params 
az group deployment create --resource-group $RG --template-file azuredeploy.json --parameters @azuredeploy.parameters.local.json --no-wait
#---------------start watching provisioning activities in azure and ssh into master-0 asap to check on the openshift origin deployment
#----

**Comment by edmacabebe** [comment]
Oops! Still a failure. 
# "oc get nodes" still lists all of the nodes to be "Not Ready"
# systemctl status origin-node.service
● origin-node.service - OpenShift Node
   Loaded: loaded (/etc/systemd/system/origin-node.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/origin-node.service.d
           └─openshift-sdn-ovs.conf
   Active: active (running) since Fri 2018-02-02 05:16:34 UTC; 1h 16min ago
     Docs: https://github.com/openshift/origin
 Main PID: 29977 (openshift)
   Memory: 64.4M
   CGroup: /system.slice/origin-node.service
           ├─29977 /usr/bin/openshift start node --config=/etc/origin/node/node-config.yaml --loglevel=2
           └─30047 journalctl -k -f

# /etc/origin/node/node-config.yaml - seems proper and it contains, w/c defines azure creds
kubeletArguments:
  cloud-provider:
    - "azure"
  cloud-config:
    - "/etc/azure/azure.conf"


Reverted to 
"enableAzure": {
	"value": "false"
}

**Comment by heatmiser** [comment]
And you're working from Microsoft/openshift-origin master?  Have you verified your Service Principal functionality?  Login with it and then create and read resources?  Can you share your azuredeploy.parameters.local.json template?

**Comment by edmacabebe** [comment]
Yes, I confirm. I've cloned the master branch only. I'll send my local
parameters in couple of days, coz im out of town with no access.

**Comment by edmacabebe** [comment]
My service principal has sufficient privileges (having thrown thousands of
euros into this already) and I'm set as owner. I can see , modify every
property in our subscription.

**Comment by edmacabebe** [comment]
my sensitive data "cleansed" azuredeploy.parameters.local.json 
---

{
	"$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
	"contentVersion": "1.0.0.0",
	"parameters": {
		"_artifactsLocation": {
			"value": "https://raw.githubusercontent.com/Microsoft/openshift-origin/master/"
		},
		"masterVmSize": { //it can be Standard_D4s_v3 depending on your subscription
			"value": "Standard_DS3" 
		},
		"infraVmSize": { //to find out, login via az login, then call az vm list-sizes --location southeastasia --output table
			"value": "Standard_DS3"
		},
		"nodeVmSize": {
			"value": "Standard_DS3"
		},
		"storageKind": {
			"value": "managed"
		},
		"openshiftClusterPrefix": {
			"value": "mycluster"
		},
		"masterInstanceCount": {
			"value": 3
		},
		"infraInstanceCount": {
			"value": 3
		},
		"nodeInstanceCount": {
			"value": 4
		},
		"dataDiskSize": {
			"value": 128
		},
		"adminUsername": {
			"value": "myadmin"
		},
		"openshiftPassword": {
			"value": "myadmin_xyz098"
		},
		"enableMetrics": {
			"value": "true"
		},
		"enableLogging": {
			"value": "true"
		},
		"enableCockpit": {
			"value": "true"
		},
		"sshPublicKey": {
			"value":  pbcopy < ~/.ssh/id_rsa.pub
		},
		"keyVaultResourceGroup": {
			"value": "myRG"
		},
		"keyVaultName": {
			"value": "myRG-kv"
		},
		"keyVaultSecret": {
			"value": "myRG-secret"
		},
		"enableAzure": {
			"value": "true"
		},
		"aadClientId": { //the tenantId as extracted from Azure CLI command as in thread above
               //az ad sp create-for-rbac -n $RG-cloudprovider --password Pass@word1 --role contributor --scopes="/subscriptions/########-####-####-####-###########/resourceGroups/$RG" |grep '"tenant":' > tenant.txt
			"value": "####"
		},
		"aadClientSecret": { //any secret you want
			"value": "Pass@word1"
		},
		"defaultSubDomainType": {
			"value": "nipio"
		},
		"defaultSubDomain": {
			"value": "domain-name-all-lowercase-if-custom-used.com"
		}
	}
}

---

**Comment by haroldwongms** [comment]
Looks like this issue is no longer valid as the issue was an error in configuration.  I am closing this issue.
