### ISSUE TITLE
Deployment fails with error "error: 'openshift-infra' already has a value (apiserver), and --overwrite is false"

### ISSUE THREAD

**Issue by swe-covis** [Microsoft/openshift-origin#71]
When trying to deploy the deployment runs into an error after a while:

`"error: 'openshift-infra' already has a value (apiserver), and --overwrite is false"`

This seems to be caused by a newly added line to deployOpenShift.sh (625) in commit 020d6aec421b5ae99e8033f8f9c0505330b4f9df:

```shell
runuser -l $SUDOUSER -c  "oc label nodes $MASTER-0 openshift-infra=apiserver"
```
Suggestion: add the overwrite flag to avoid failing if label has already been set
```
runuser -l $SUDOUSER -c  "oc label nodes $MASTER-0 openshift-infra=apiserver --overwrite=true"
```

**Comment by swe-covis** [comment]
After adding the flag I was able to deploy successfully so I opened a PR: https://github.com/Microsoft/openshift-origin/pull/72

**Comment by haroldwongms** [comment]
Closing this issue as PR was merged.
