### ISSUE TITLE
docker group is not created

### ISSUE THREAD

**Issue by Kaizhe** [Microsoft/openshift-origin#73]
```
[azureuser@setup-dev321a4-node-2 ~]$ cat /etc/group | grep docker
dockerroot:x:992:

```

**Comment by vincepower** [comment]
The dockerroot user and group are added by the installation of docker which is a requirement for OpenShift. There is also a volume group created for docker on each node that is used for storage which can be displayed with "sudo vgdisplay".

**Comment by haroldwongms** [comment]
Closing as this is not an issue.
