### ISSUE TITLE
SSH for any OpenShift cluster node - either through Azure console or local console doesn't work

### ISSUE THREAD

**Issue by tgj** [Microsoft/openshift-origin#79]
Hi all, 

When the deployment gets to the Ansible step (or the OpenShiftDeployment step), the Azure instance running Ansible cannot connect ot any OpenShift cluster node; causing the deployment to fail. I tried to SSH into the master0 node via: 

`ssh -p 2200 <name-of-openshift-admin>@<public-ip-to-master-0-node>`

and the operation timed out.

I've verified that I'm using the correct public and private SSH key, and I've attached the stdout of the error log.

Any thoughts?

**Comment by tgj** [comment]
[errorlog.txt](https://github.com/Microsoft/openshift-origin/files/1943734/errorlog.txt)

**Comment by haroldwongms** [comment]
When you SSH to master-0, please verify that the key stored in .ssh is indeed the correct private key.  Also make sure you aren't using a passphrase.

**Comment by haroldwongms** [comment]
Oops.  Didn't read close enough.  If you are using the template, there should only be one public IP for the master LB, not for each master node.  If you can't SSH to the master, then double check the NSG rules.  You can also just deploy a new VM from the portal and make sure the public key you are using works for a new VM deployment as a troubleshooting step.

**Comment by haroldwongms** [comment]
@tgj I totally missed the errorlog.txt.  I took a look at that and it looks like you applied a passphrase to the private key or the private key is incorrect.  It may also be that when you created the secret in the keyvault, you did not format things correctly.

**Comment by haroldwongms** [comment]
Since there has been no response, I am closing this issue.

**Comment by wely** [comment]
@haroldwongms I'm facing similar issue ssh-in to the master node.

I have successfully deployed thru the "Deploy to Azure" button with the instruction on this readme.md. 

Few question to clarify:
1. it seems that the template generated NIC without any public ip.
![nic](https://user-images.githubusercontent.com/1658657/40419975-7742fd78-5eb9-11e8-99b6-e9f8f2ab3464.JPG)
2. When i try to connect via ssh with public ip of the master node VM, i got this error:
![ssh error](https://user-images.githubusercontent.com/1658657/40420064-b4372ba0-5eb9-11e8-9863-ab625b23df09.JPG)
