### ISSUE TITLE
Pods unable to resolve kubernetes.default.svc.cluster.local

### ISSUE THREAD

**Issue by SitoCH** [Microsoft/openshift-origin#9]
Hello,
I used this template and everything works fine except that I can't deploy origin-metrics because the pods can't resolve kubernetes.default.svc.cluster.local.
The issue seems to be related to a wrong /etc/resolv.conf on every node that is being overwritten by the DHCP with Azure's  default nameservers.
Do you know how it'd be possible to fix this issue?

Thank you

**Comment by BorisB2015** [comment]
@haroldwongms - please take a look. Thanks!

**Comment by SitoCH** [comment]
I investigated the issue and it seems that right after the deployment everything is working. After I run the origin-metrics ansible script the nameservers are overwritten by the DHCP using only the ones from Azure...

**Comment by haroldwongms** [comment]
Can you share the exact command (with all parameters) that you are using to install metrics?  Thanks.

**Comment by SitoCH** [comment]
Yes sure. I just login via using SSH and I run:

```
ansible-playbook openshift-ansible/playbooks/byo/openshift-cluster/openshift-metrics.yml \
   -e openshift_metrics_install_metrics=True \
   -e openshift_metrics_hawkular_hostname=myhostname.com \
   -e openshift_metrics_cassandra_storage_type=emptydir \
   -e openshift_metrics_duration=1 \
   -e openshift_metrics_cassandra_request_memory=128M \
   -e openshift_metrics_hawkular_request_memory=128M \
   -e openshift_metrics_heapster_request_memory=128M 
```

**Comment by SitoCH** [comment]
This is really strange, I just woke up and double checked everything. I deleted the pod and now it has the right resolv.conf...is it possibile that this is an intermitted failure and after some time the node's resolv.conf get overwritten again with the right nameservers?

**Comment by SitoCH** [comment]
After the initial setup now the resolv.conf is always correct. I think this behavior appears only on newly created clusters so I'm closing this issue since you only need to wait a bit to get everything right.
