### ISSUE TITLE
Failed o deploy v3.9 using this openshift-origin Azure template 

### ISSUE THREAD

**Issue by kumardil91** [Microsoft/openshift-origin#95]
RUNNING HANDLER [openshift_node : restart node] ************************************************************************************************************************************************
FAILED - RETRYING: restart node (3 retries left).
FAILED - RETRYING: restart node (3 retries left).
FAILED - RETRYING: restart node (3 retries left).
FAILED - RETRYING: restart node (2 retries left).
FAILED - RETRYING: restart node (2 retries left).
FAILED - RETRYING: restart node (2 retries left).

After running again , this is showing me the another error: 

-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit origin-node.service has begun starting up.
Jul 09 05:21:27 mycluster-node-0 dnsmasq[45079]: setting upstream servers from DBus
Jul 09 05:21:27 mycluster-node-0 dnsmasq[45079]: using nameserver 168.63.129.16#53
Jul 09 05:21:27 mycluster-node-0 dnsmasq[45079]: using nameserver 127.0.0.1#53 for domain in-addr.arpa
Jul 09 05:21:27 mycluster-node-0 dnsmasq[45079]: using nameserver 127.0.0.1#53 for domain cluster.local
Jul 09 05:21:27 mycluster-node-0 origin-node[29232]: I0709 05:21:27.261830   29232 start_node.go:309] Reading node configuration from /etc/origin/node/node-config.yaml
Jul 09 05:21:27 mycluster-node-0 origin-node[29232]: I0709 05:21:27.263229   29232 start_node.go:479] Starting node mycluster-node-0 (v3.9.0+ba7faec-1)
Jul 09 05:21:27 mycluster-node-0 origin-node[29232]: W0709 05:21:27.263376   29232 server.go:185] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Pleas
Jul 09 05:21:27 mycluster-node-0 origin-node[29232]: Flag --require-kubeconfig has been deprecated, You no longer need to use --require-kubeconfig. This will be removed in a future version. Pr
Jul 09 05:21:27 mycluster-node-0 origin-node[29232]: I0709 05:21:27.265902   29232 start_node.go:535] kubelet [--address=0.0.0.0 --allow-privileged=true --anonymous-auth=true --authentication-
Jul 09 05:21:27 mycluster-node-0 origin-node[29232]: I0709 05:21:27.265958   29232 feature_gate.go:220] feature gates: &{{} map[]}
Jul 09 05:21:27 mycluster-node-0 origin-node[29232]: I0709 05:21:27.265994   29232 controller.go:114] kubelet config controller: starting controller
Jul 09 05:21:27 mycluster-node-0 origin-node[29232]: I0709 05:21:27.266000   29232 controller.go:118] kubelet config controller: validating combination of defaults and flags
Jul 09 05:21:27 mycluster-node-0 origin-node[29232]: I0709 05:21:27.267450   29232 node.go:151] Initializing SDN node of type "redhat/openshift-ovs-multitenant" with configured hostname "myclu
Jul 09 05:21:27 mycluster-node-0 systemd[1]: Started Kubernetes systemd probe.
-- Subject: Unit run-29243.scope has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit run-29243.scope has finished starting up.
--
-- The start-up result is done.
Jul 09 05:21:27 mycluster-node-0 systemd[1]: Starting Kubernetes systemd probe.
-- Subject: Unit run-29243.scope has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit run-29243.scope has begun starting up.
Jul 09 05:21:27 mycluster-node-0 origin-node[29232]: I0709 05:21:27.274680   29232 mount_linux.go:210] Detected OS with systemd
Jul 09 05:21:27 mycluster-node-0 origin-node[29232]: W0709 05:21:27.274847   29232 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Jul 09 05:21:27 mycluster-node-0 origin-node[29232]: I0709 05:21:27.279671   29232 server.go:236] Version: v1.9.1+a0ce1bc657
Jul 09 05:21:27 mycluster-node-0 origin-node[29232]: I0709 05:21:27.279705   29232 feature_gate.go:220] feature gates: &{{} map[]}
Jul 09 05:21:27 mycluster-node-0 origin-node[29232]: W0709 05:21:27.279858   29232 server.go:334] --require-kubeconfig is deprecated. Set --kubeconfig without using --require-kubeconfig.
Jul 09 05:21:27 mycluster-node-0 origin-node[29232]: F0709 05:21:27.280180   29232 server.go:173] failed to run Kubelet: could not init cloud provider "azure": No credentials provided for AAD
Jul 09 05:21:27 mycluster-node-0 systemd[1]: origin-node.service: main process exited, code=exited, status=255/n/a
Jul 09 05:21:27 mycluster-node-0 dnsmasq[45079]: setting upstream servers from DBus
Jul 09 05:21:27 mycluster-node-0 dnsmasq[45079]: using nameserver 168.63.129.16#53
Jul 09 05:21:27 mycluster-node-0 systemd[1]: Failed to start OpenShift Node.
-- Subject: Unit origin-node.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit origin-node.service has failed.
--
-- The result is failed.
Jul 09 05:21:27 mycluster-node-0 systemd[1]: Unit origin-node.service entered failed state.
Jul 09 05:21:27 mycluster-node-0 systemd[1]: origin-node.service failed.

**Comment by haroldwongms** [comment]
@kumardil91 Can you please verify that the error is still occurring or if you are able to install the Origin (OKD) 3.9 cluster?  Thank you.

**Comment by haroldwongms** [comment]
Closing as I have not heard anything back and it has been over 2 months.
